services:
  database:
    image: br_database
    build:
      context: ./database/
    environment:
      POSTGRES_PASSWORD: "zq123edc"
    networks:
      - badreads_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  back:
    image: br_backend
    build:
      context: ./backend/
    ports:
      - "8080:8080"
    networks:
      - badreads_net
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5

  front:
    image: br_frontend
    build:
      context: ./frontend/
    ports:
      - "3000:3000"
    networks:
      - badreads_net
    depends_on:
      back:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  badreads_net:
      name: badreads_net
      external: true
