on:
  release:
    types: [prereleased]

jobs:
  build-production-locally:
    runs-on: [self-hosted, production]
    steps:
      - uses: actions/checkout@v4

      - name: bring it down if up
        run: docker compose down

      - name: Build the Backend image
        run: docker compose build backend

      - name: Build the database image
        run: docker compose build database

      - name: Build the server image
        run: |
          docker compose build server

  deploy-production:
    needs: build-production
    runs-on: [self-hosted, production]
    steps:
      - name: deploy to production locally
        run: docker compose up -d

      - name: check services health
        run: ./check_health.sh -t 20 database backend
        working-directory: scripts
