on:
  push:
    branches: ["master"]

jobs:
  deploy-production:
    runs-on: [self-hosted, production]
    steps:
      - uses: actions/checkout@v4

      - name: bring it down if up
        run: docker compose down

      - name: remove the defaults to prevent accidental fills.
        run: rm -f .env

      - name: Write secrets to .env
        run: |
          cat > .env <<'EOF'
          SUPER_SECRET_PASSWORD=${{ secrets.SUPER_SECRET_PASSWORD }}
          SERVER_PORT_EXPOSED1=${{ secrets.SERVER_PORT_EXPOSED1 }}
          SERVER_PORT_EXPOSED2=${{ secrets.SERVER_PORT_EXPOSED2 }}
          SSL_CERTIFICATE=${{ secrets.SSL_CERTIFICATE }}
          SSL_KEY=${{ secrets.SSL_KEY }}
          SERVER_NAME=${{ secrets.SERVER_NAME }}
          SSL_CERT_VOLUME=${{ secrets.SSL_CERT_VOLUME }}
          SSL_KEY_VOLUME=${{ secrets.SSL_KEY_VOLUME }}
          EOF

      - name: Build the images
        run: |
          docker compose build \
            --build-arg SERVER_NAME=${{ secrets.SERVER_NAME }} \

      - name: deploy to production
        run: docker compose up -d

      - name: check services health
        run: ./check_health.sh -t 20 database backend
        working-directory: scripts

      - name: delete secret envs
        if: always()
        run: rm -f .env
