on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: bring it down if up
        run: docker compose down

      - name: Build the Backend image
        run: docker compose build backend

      - name: Build the frontend image
        run: docker compose build frontend

      - name: Build the database image
        run: docker compose build database

      - name: deploy the app locally
        run: docker compose up -d && docker compose logs --until 1m

      - name: check services health
        run: ./check_health.sh -t 30 database backend frontend
        working-directory: scripts
