on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: bring it down if up
        run: docker compose down

      - name: Build the Backend image
        run: docker compose build backend

      - name: Build the frontend image
        run: docker compose build frontend

      - name: Build the database image
        run: docker compose build database

  deploy-localy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: remove default env and set the value
        run: rm .env
        env:
          SUPER_SECRET_PASSWORD: ${{ secrets.DB_PASSWORD }}
      - name: deploy locally
        run: docker compose up -d

      - name: check services health
        run: ./check_health.sh -t 20 database backend frontend
        working-directory: scripts
